### ISSUE TITLE
How would this plugin work for existing multisite installations?

### ISSUE THREAD

**Issue by kantorcodes** [humanmade/amf-wordpress#11]
Figure me for my ignorance - I am currently researching different options for implementing a "global media library" for an existing multisite. So, I was wondering, let's say I have an existing multisite with tons of sites which already have their own media uploaded. Would I be able to utilize this plugin and:
 1. Retain all existing media uploads, either by searching when adding media, or when accessing attempting to access a media_id that might be stored as metadata on a post or some other method? 
 2. Will calling functions like `wp_get_attachment_image_src`  in a subsite still work? 
 2. Be able to upload media from all subsites, or would that be limited only to the "source"?
 3. Will I be able to set the source dynamically via or filter or other mechanism than updating the settings?
 4. If no source is set in the Media settings, does that effectively make the subsite a source itself?

**Comment by kantorcodes** [comment]
Also, followup question as I am giving this plugin a go, is it normal for only a handful of images to show up in the Media library after setting a remote source? I can't seem to search or sort by date.

**Comment by roborourke** [comment]
Hey @kantorcodes, to answer your questions we are building out this plugin and the asset manager framework itself to build a global media library feature for [Altis](https://www.altis-dxp.com). Other than that the functionality is current limited to what was needed for a client project at the time.

We've just added support for multiple providers including local media, so you can switch which media library you're using. You can also prevent local media showing as an option and force everyone to use a single source if desired but note that currently upload support has not been finalised.

> Retain all existing media uploads, either by searching when adding media, or when accessing attempting to access a media_id that might be stored as metadata on a post or some other method?

All existing media will stay as is, AMF creates a local attachment post in the database whenever an external asset is selected so you always have a real ID - using it in post meta etc should be seamless.

> Will calling functions like wp_get_attachment_image_src in a subsite still work?

Yeah that's the plan, everything should be working with AMF 0.12.0 and the latest version of this plugin.

> Be able to upload media from all subsites, or would that be limited only to the "source"?

Eventually you could upload media from subsites but currently limited to the source.

> Will I be able to set the source dynamically via or filter or other mechanism than updating the settings?

There's the constant that can be defined, if a filter would be useful you can create an issue or a pull request.

> If no source is set in the Media settings, does that effectively make the subsite a source itself?

No, I think it'll just break in that instance, or the source site won't show as an option if you have local media enabled still.

> Also, followup question as I am giving this plugin a go, is it normal for only a handful of images to show up in the Media library after setting a remote source? I can't seem to search or sort by date.

Not seen that myself. I'd look for any errors in the JS console or PHP error log to try and narrow it down. If the problem can be reproduced consistently then best to create an issue with those steps and a description of the problem.

**Comment by roborourke** [comment]
Closing out as stale, hopefully my reply answered your questions :)
