### ISSUE TITLE
Search/filter options in the media screen appear not to function

### ISSUE THREAD

**Issue by kantorcodes** [humanmade/amf-wordpress#12]
👋  I have been digging a bit more into this plugin and have noticed that search/pagination does not appear to work for my install. Every load, the ajax request appears to look like the following:

```
/wp-json/wp/v2/media?page=1&per_page=40&order=desc
```

However, upon scrolling the actual media library, subsequent ajax requests are not triggered to fetch page = 2, 3, etc

Additionally, by toggling the date dropdown, or searching the search box, yields zero results. Upon digging into the media endpoint, it actually doesn't look like the `search` parameter yields any results.

Example Request: 
```
/wp-json/wp/v2/media?search=credit
```

Should search by media work? Or would we need to use a different endpoint, ie, search instead?

**Comment by roborourke** [comment]
Yeah search is a valid parameter for that endpoint so it should work. Not seen the pagination issues before. Are you seeing the `X-WP-*` headers in the response?

**Comment by tfrommen** [comment]
Hm, using the _Search_ field works fine for me, both in the Media Library and in a Media Modal when editing a post using the Block Editor.

**Comment by roborourke** [comment]
@t-fritsch the load more button and those headers in the admin-Ajax response were  only added in WP 5.8, this plugin was written before it’s release and hasn’t been tested with 5.8 yet, at least not by us

**Comment by t-fritsch** [comment]
Thanks @roborourke, I guess it's more a problem in AMF then, I saw the issue https://github.com/humanmade/asset-manager-framework/issues/38, I'll comment there

**Comment by roborourke** [comment]
Correct @t-fritsch! - I'll close this in favour of that other issue.
