### ISSUE TITLE
Load more button not showing up

### ISSUE THREAD

**Issue by t-fritsch** [humanmade/amf-wordpress#19]
Hi,

I'm trying the latest version of this plugin since it is now compatible with WP5.8.

Unfortunately, even with the X-WP-Total and X-WP-TotalPages response headers, the "Load more" button stays hidden in my website.

In fact I've noticed that :
- the number of items returned by the api call to `admin-ajax.php` with `action="query-attachments"` and `query[provider] ="wordpress"` is below the `posts_per_page` parameter even when there are a lot more media
    
    ![image](https://user-images.githubusercontent.com/10920280/143489445-29503d84-a92b-4893-a36c-4a39d09c3cd1.png)

    ![image](https://user-images.githubusercontent.com/10920280/143489696-e4ea611d-e8e3-4619-ba29-ea1794199bf6.png)

- media library then displays the number of items on the bottom of the page 
![image](https://user-images.githubusercontent.com/10920280/143488592-006a75eb-8a93-41ee-b65d-bcc18123a0eb.png)
- since the number of items returned by the api call is less than posts_per_page, the Load More button doesn't show up : see https://github.com/WordPress/WordPress/blob/master/wp-includes/js/media-models.js#L1353-L1356

I've tried to understand why the provider ignores some media and I wonder if it's not related to https://core.trac.wordpress.org/ticket/50410
 
It seems that the way the plugin loads medias adds some filters to the query that original wordpress ajax request does not add.

Any idea how to fix this ?

**Comment by t-fritsch** [comment]
hello @roborourke !

Did you have time to investigate on this ? Or any clue on where to look at by my side ?

thanks for your help 🙏

**Comment by roborourke** [comment]
I’d not seen it til now sorry. I imagine it’s not calculating the found posts properly, either because of further filtering on the client side or some incorrect server side code. We do need to improve mine type support more generally, providers can’t declare supported types right now

**Comment by t-fritsch** [comment]
thanks for your reply

I digged into this a little more and it seems that the attachments that are missing are those with `post_parent` value that's not `0`.

It looks like WP API doesn't return such media with `post_parent`

**Comment by t-fritsch** [comment]
OK, I think I've found the reason of the problem :

The REST API checks "read permissions" on every media before returning it. If the media has a `post_parent`, it also checks the parent's read permissions : 

https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1616-L1621

if the parent post is a custom post type, it checks if that custom post type is readable through REST API :

https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1601-L1603

https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1582

SO, the problem here is that my Custom post types were not registered with :
```php
'show_in_rest' => true,
```

Adding this flag to every CPT allows :
- REST API to return every media even those attached to CPT
- AMF to return the correct number of items 
- and Media library to show the "Load More" button !

I'm closing this issue since it's not an amf-wordpress bug but related to wp api : https://core.trac.wordpress.org/ticket/42785 (`show_in_rest` should be `true` by default when `public` is `true`).

Thanks for your help !

I've got one more question, maybe you can help : why amf-wordpress uses wp-api and not a WP-Query ? Is it something that seems doable (maybe through a custom Provider) ?
In the case of a multisite install, every media that we share are in the same DB, querying the DB could probably make it easier to control what shows up and save an http request.

**Comment by rmccue** [comment]
> I've got one more question, maybe you can help : why amf-wordpress uses wp-api and not a WP-Query ? Is it something that seems doable (maybe through a custom Provider) ?
> In the case of a multisite install, every media that we share are in the same DB, querying the DB could probably make it easier to control what shows up and save an http request.

Plugins won't be changed when switching between sites, so behaviour may not work consistently if you handle requests internally rather than re-initialising WP.

**Comment by roborourke** [comment]
Yeah, plus easier for us to write and maintain one method of access. Others have written PRs to try and use direct db queries but I don't think we'll support that approach officially here. Happy for others to publish their own providers and PR the readme here to add links to them.

Thanks for digging deeper and finding the issue! Hopefully it'll be fixed in core soon.

**Comment by tfrommen** [comment]
@t-fritsch PR #13 has a bit of context and reasoning why AMF WordPress uses the media REST API endpoint on the source site, instead of internal requests.
