### ISSUE TITLE
Current state of development update?

### ISSUE THREAD

**Issue by theMikeD** [humanmade/amf-wordpress#20]
This looks promising, but hasn't been touched for quite a while. Do you know if this is in production use anywhere?

**Comment by rmccue** [comment]
It is; AMF and AMF WordPress are included in [the Altis Media module](https://github.com/humanmade/altis-media/), are supported as part of the Altis Cloud platform, and are in use across all Altis-hosted sites. :)

**Comment by theMikeD** [comment]
OK I get that you might be using it in your own products :) 

Let me try from another angle: The code is marked as alpha state, but has not been touched in three years. Is this still a viable product with a roadmap given the lack of active development?

**Comment by rmccue** [comment]
The project is stable and works, but there's no individual roadmap for it, as it's not a "product" we sell individually. Rather, it's a component of a larger system which can be used standalone.
