### ISSUE TITLE
If I use this for a while and the decide not wo, what happens?

### ISSUE THREAD

**Issue by theMikeD** [humanmade/amf-wordpress#21]
Let's say I implement this plugin and everything goes swimmingly. Then I need to stop using it.

Is there any documentation, or is it even possible, to disable this plugin and somehow have the media keep working? Basically: if the decision is made to stop using this plugin once it's been in use for a while, is there a way to un-do what it does and preserve media availability? I assume this would involve copying media from one library to another and replacing existing with new, which sounds like a tall order.

Or is the use of this plugin a one-way street?

**Comment by rmccue** [comment]
This is a better question for the AMF repo than here.

AMF isn't designed to be enabled and then turned off later. While it creates a local ("shadow") copy of the remote asset, things like URLs etc can be filtered dynamically by AMF. As such, I would not recommend this process.

**Comment by theMikeD** [comment]
The answer implies that this should not be used as a standalone plugin, even though it is presented as one, which is a good thing to be aware of. Thanks.
